
application: danny

version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on



handlers:


- url: /myadmin
  static_dir: myadmin
  expiration: "7d"


- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'


- url: /_ah/admin.*
  script: google.appengine.ext.admin.application
  login: admin




- url: /.*
  script: djangoappengine.main.application



libraries:
- name: django
  version: latest




